remote_theme: jeffreytse/jekyll-theme-yat
title: Oscar Smith-Jones
email: ozzysmithjoneswork@gmail.com
author: Oscar Smith-Jones
home:
  heading: "Oscar Smith-Jones"
  subheading: "Associate Software Engineer"
 header_pages:
   - Engine.md


